### ISSUE TITLE
problem with schema form

### ISSUE THREAD

**Issue by mhhf** [mike-marcacci/objectpath#4]
I'm new to angular and maybe I oversee something, but I couldn't get it to work out of the box with angular-schema-form. I got the following Error:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module VSPApp due to:
Error: [$injector:modulerr] Failed to instantiate module ObjectPath due to:
Error: [$injector:nomod] Module 'ObjectPath' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.15/$injector/nomod?p0=ObjectPath
    at REGEX_STRING_REGEXP (http://localhost:3000/bower_components/angular/angular.js:63:12)
    at http://localhost:3000/bower_components/angular/angular.js:1774:17
    at ensure (http://localhost:3000/bower_components/angular/angular.js:1698:38)
    at module (http://localhost:3000/bower_components/angular/angular.js:1772:14)
    at http://localhost:3000/bower_components/angular/angular.js:4115:22
    at forEach (http://localhost:3000/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4099:5)
    at http://localhost:3000/bower_components/angular/angular.js:4116:40
    at forEach (http://localhost:3000/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4099:5)
http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=ObjectPath&p1=Erro…2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A4099%3A5)
    at REGEX_STRING_REGEXP (http://localhost:3000/bower_components/angular/angular.js:63:12)
    at http://localhost:3000/bower_components/angular/angular.js:4138:15
    at forEach (http://localhost:3000/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4099:5)
    at http://localhost:3000/bower_components/angular/angular.js:4116:40
    at forEach (http://localhost:3000/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4099:5)
    at createInjector (http://localhost:3000/bower_components/angular/angular.js:4025:11)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1452:20)
    at bootstrap (http://localhost:3000/bower_components/angular/angular.js:1473:12)
http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=VSPApp&p1=Error%3A…F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A1473%3A12)
```

the reason for this was that ObjectPath wasn't registered as an angular module yet, because `ObjectPath.registerModule(angular)` wasn't called anywhere. After I added the following lines to `ObjectPath.js:97` it worked:

```
    // Angular JS
    else if (typeof angular === 'object') {
    ObjectPath.registerModule(angular);
        window.ObjectPath = ObjectPath;
    }
```

**Comment by mike-marcacci** [comment]
Hey @mhhf, thanks for the issue here. This used to be done automatically, but had unfortunate consequences when loaded over requireJS or AMD.

Since then (many months ago) Schema-Form has by default been dependent on `window.ObjectPath` instead of the angular module `ObjectPath`. Can you check the version of Schema-Form that you're using?

Also, are you using any third-party custom elements that may be trying to access ObjectPath themselves?

**Comment by mike-marcacci** [comment]
Sorry for never replying to this; I'm going to close due to the issue's age. Please reopen if it still exists.
